# -*- coding: utf-8 -*-
"""sem exam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itlRaV7wQHBcR-rte6xD3GQDhBAHH2-h
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

data=pd.read_csv("/content/Mall_Customers.csv")
data

x=data.iloc[:,[3,4]].values
x

wc=[]
for i in range(1,11):
  Kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  Kmeans.fit(x)
  wc.append(Kmeans.inertia_)
plt.plot(range(1,11),wc)
plt.title("the Elbow method Graph")
plt.xlabel("number of clusters")
plt.ylabel("WCSS")
plt.show()

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_predict=kmeans.fit_predict(x)
y_predict

plt.scatter(x[y_predict==0,0],x[y_predict==0,1],s=100,c='red',label='cluster1')
plt.scatter(x[y_predict==1,0],x[y_predict==1,1],s=100,c='yellow',label='cluster2')
plt.scatter(x[y_predict==2,0],x[y_predict==2,1],s=100,c='blue',label='cluster3')
plt.scatter(x[y_predict==3,0],x[y_predict==3,1],s=100,c='pink',label='cluster4')
plt.scatter(x[y_predict==4,0],x[y_predict==4,1],s=100,c='green',label='cluster5')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=300,c='black',label='Centroids')
plt.xlabel('Annual Income(k$)')
plt.ylabel('Spending Score(1-100)')
plt.legend()
plt.show()

